SET hive.exec.dynamic.partition=true;
SET hive.exec.dynamic.partition.mode=nonstrict;
INSERT INTO TABLE CDW_SAPP_D_TIME_PARTITIONED
PARTITION(QUARTER)
SELECT TIMEID, DAY, MONTH, YEAR, TRANSACTION_ID, QUARTER
FROM CDW_SAPP_D_TIME_EXTERNAL;